#!/usr/bin/env bash

applyModule() {
	local action="$1"

	# Depollueurs
	#	iptables -m comment --comment "NO_LOG_POLLUTION:ICMP" $action INPUT -p icmp -j DROP
	#	iptables -m comment --comment "NO_LOG_POLLUTION: TCP" $action INPUT -p tcp --match multiport --dports 21:25,80,81,222,443,2222,3306,3389 -j DROP

	# Logs
	iptables -m comment --comment "Logs        " $action   INPUT -j LOG --log-prefix "  [INPUT DROPPED] "
	iptables -m comment --comment "Logs        " $action  OUTPUT -j LOG --log-prefix " [OUTPUT DROPPED] "
	iptables -m comment --comment "Logs        " $action FORWARD -j LOG --log-prefix "[FORWARD DROPPED] "
}

