#!/usr/bin/env bash

iptables -m comment --comment "OUT HTTP           " $actFlg TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport   80 -j ACCEPT
iptables -m comment --comment "OUT HTTP           " $actFlg TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport   80 -j ACCEPT

