#!/usr/bin/env bash

apply() {
	local action="$1"

	iptables -m comment --comment "OUT SMTP           " $action TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport   25 -j ACCEPT
	iptables -m comment --comment "OUT SMTP           " $action TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport   25 -j ACCEPT
}

