#!/usr/bin/env bash

iptables -m comment --comment "OUT NTP            " $actFlg UDP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p udp --dport  123 -j ACCEPT
iptables -m comment --comment "OUT NTP            " $actFlg UDP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p udp --sport  123 -j ACCEPT

