#!/usr/bin/env bash

apply() {
	local action="$1"

	iptables -m comment --comment "OUT DNS            " $action UDP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p udp --dport   53 -j ACCEPT
	iptables -m comment --comment "OUT DNS            " $action UDP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p udp --sport   53 -j ACCEPT
}

