#!/usr/bin/env bash

iptables -m comment --comment "OUT Whois          " $actFlg TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport   43 -j ACCEPT
iptables -m comment --comment "OUT Whois          " $actFlg TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport   43 -j ACCEPT
iptables -m comment --comment "OUT Whois          " $actFlg TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport 4321 -j ACCEPT
iptables -m comment --comment "OUT Whois          " $actFlg TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport 4321 -j ACCEPT

