#!/usr/bin/env bash

apply() {
	local action="$1"

	iptables -m comment --comment "OUT Whois          " $action TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport   43 -j ACCEPT
	iptables -m comment --comment "OUT Whois          " $action TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport   43 -j ACCEPT
	iptables -m comment --comment "OUT Whois          " $action TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport 4321 -j ACCEPT
	iptables -m comment --comment "OUT Whois          " $action TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport 4321 -j ACCEPT
}

