#!/usr/bin/env bash

applyModule() {
	local action="$1"

	iptables  -m comment --comment "OUT SSH            " $action TCP_OUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport   22 -j ACCEPT
	iptables  -m comment --comment "OUT SSH            " $action TCP_IN  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport   22 -j ACCEPT

	ip6tables -m comment --comment "OUT SSH            " $action OUTPUT -o $NTWK_INTFCE -m conntrack --ctstate NEW,ESTABLISHED -p tcp --dport   22 -j ACCEPT
	ip6tables -m comment --comment "OUT SSH            " $action INPUT  -i $NTWK_INTFCE -m conntrack --ctstate     ESTABLISHED -p tcp --sport   22 -j ACCEPT
}

