#!/bin/bash

[ -n "$IPTABLES_INIT_LIB" ] && source $IPTABLES_INIT_LIB || exit 1

[ -n "$FORWARDING" ] || exit 0
TABLE='filter'
addToChain FORWARD_ALLOWED RETURN --source      $FORWARDING
addToChain FORWARD_ALLOWED RETURN --destination $FORWARDING
addToChain FORWARD_ALLOWED RETURN --source 0.0.0.0 --destination 255.255.255.255
