#!/bin/bash

[ -n "$IPTABLES_INIT_LIB" ] && source $IPTABLES_INIT_LIB || exit 1

TABLE='filter'

openInStreams() {
	local port="$1"
	shift
	local clients="$@"
	[ -n "$clients" ] && {
		if [ "$clients" == 'all' ]; then
			addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --dport $port
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --sport $port
		else
			for client in $clients; do
				addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $client --dport $port
				addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $client --sport $port
			done
		fi
	}
}

openInStreams   80 $IN_HTTP_CLI_ALLOWED
openInStreams  443 $IN_HTTPS_CLI_ALLOWED
openInStreams   22 $IN_SSH_CLI_ALLOWED
openInStreams 3142 $IN_APT_CLI_ALLOWED
openInStreams 8140 $IN_PUPPET_CLI_ALLOWED
