#!/bin/bash

[ -n "$IPTABLES_INIT_LIB" ] && source $IPTABLES_INIT_LIB || exit 1

TABLE='filter'

[ "$OUT_WHOIS" == 'true' ] && {
	addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp  --dport  43
}

[ -n "$OUT_SSH_SRV_ALLOWED" ] && {
	if [ "$OUT_SSH_SRV_ALLOWED" == 'all' ]; then
		addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --dport 22
		addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --sport 22
	else
		for server in $OUT_SSH_SRV_ALLOWED; do
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $server --dport 22
			addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $server --sport 22
		done
	fi
}

[ -n "$OUT_APT_SRV_ALLOWED" ] && {
	if [ "$OUT_APT_SRV_ALLOWED" == 'all' ]; then
		addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --dport 3142
		addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --sport 3142
	else
		for server in $OUT_APT_SRV_ALLOWED; do
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $server --dport 3142
			addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $server --sport 3142
		done
	fi
}

[ -n "$OUT_PUPPET_SRV_ALLOWED" ] && {
	if [ "$OUT_PUPPET_SRV_ALLOWED" == 'all' ]; then
		addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --dport 8140
		addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --sport 8140
	else
		for server in $OUT_PUPPET_SRV_ALLOWED; do
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $server --dport 8140
			addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $server --sport 8140
		done
	fi
}

[ -n "$OUT_HTTP_SRV_ALLOWED" ] && {
	if [ "$OUT_HTTP_SRV_ALLOWED" == 'all' ]; then
		addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --dport 80
	else
		for server in $OUT_HTTP_SRV_ALLOWED; do
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $server --dport 80
		done
	fi
}

[ -n "$OUT_HTTPS_SRV_ALLOWED" ] && {
	if [ "$OUT_HTTPS_SRV_ALLOWED" == 'all' ]; then
		addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --dport 443
	else
		for server in $OUT_HTTPS_SRV_ALLOWED; do
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $server --dport 443
		done
	fi
}

[ "$OUT_GITHUB" == 'true' ] && {
	addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination 192.30.252/24 --dport  22
	addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination 192.30.252/24 --dport 443
}
