#!/bin/bash

[ -n "$IPTABLES_INIT_LIB" ] && source $IPTABLES_INIT_LIB || exit 1

TABLE='filter'

openOutStreams() {
	local port="$1"
	shift
	local servers="$@"
	[ -n "$servers" ] && {
		if [ "$servers" == 'all' ]; then
			addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --dport $port
			addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --sport $port --match state --state ESTABLISHED,RELATED --dport 1024:
		else
			for server in $servers; do
				addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $server --dport $port
				addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $server --sport $port --match state --state ESTABLISHED,RELATED --dport 1024:
			done
		fi
	}
}

openOutStreams   80 $OUT_HTTP_SRV_ALLOWED
openOutStreams  443 $OUT_HTTPS_SRV_ALLOWED
openOutStreams   22 $OUT_SSH_SRV_ALLOWED
openOutStreams 3142 $OUT_APT_SRV_ALLOWED
openOutStreams 8140 $OUT_PUPPET_SRV_ALLOWED

[ "$OUT_GITHUB" == 'true' ] && {
	openOutStreams   22 '192.30.252/22'
	openOutStreams  443 '192.30.252/22'
}

[ "$OUT_WHOIS" == 'true' ] && {
	openOutStreams 43 'all'
}

