#!/bin/bash

[ -n "$IPTABLES_INIT_LIB" ] && source $IPTABLES_INIT_LIB || exit 1

TABLE='filter'

# Allow client to create broadcast and multicast request
#     >> Allow DHCP request / response
addToChain UDP_INPUT_ALLOWED  RETURN --protocol udp --source-port 67 --destination-port 68 # checked
addToChain UDP_OUTPUT_ALLOWED RETURN --protocol udp --source-port 68 --destination-port 67 # checked

# All packets allowed must be returned. Others are dropped.
addToChain TCP_INPUT_ALLOWED   DROP TCP_IN_REFUSED
addToChain UDP_INPUT_ALLOWED   DROP UDP_IN_REFUSED
addToChain ICMP_INPUT_ALLOWED  DROP ICMP_IN_REFUSED

addToChain TCP_OUTPUT_ALLOWED  DROP TCP_OUT_REFUSED
addToChain UDP_OUTPUT_ALLOWED  DROP UDP_OUT_REFUSED
addToChain ICMP_OUTPUT_ALLOWED DROP ICMP_OUT_REFUSED

addToChain FORWARD_ALLOWED     DROP FORWARD_REFUSED

