#!/bin/bash

persoFilter() {

  ######################################################################
  # Forward

  # VM
  addToChain FORWARD_ALLOWED RETURN --source      192.168.1/24
  addToChain FORWARD_ALLOWED RETURN --destination 192.168.1/24
  addToChain FORWARD_ALLOWED RETURN --source 0.0.0.0 --destination 255.255.255.255


  ######################################################################
  # Inbound

  # SSH
  for client in trust1 trust2; do
    addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $client --dport    22
    addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $client --sport    22
  done

  # HTTP
  addToChain TCP_INPUT_ALLOWED   RETURN --protocol tcp --source localhost --destination localhost --dport 80
  addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp --source localhost --destination localhost --sport 80
  for client in trust1 trust2 trust3 trust4 trust5; do
    addToChain TCP_INPUT_ALLOWED   RETURN --protocol tcp --source      $client --dport 80
    addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp --destination $client --sport 80
  done
  # addToChain TCP_INPUT_ALLOWED   RETURN --protocol tcp --dport 80
  # addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp --sport 80

  # Proxy APT
  for client in trust1 trust2 trust3 trust4 trust5; do
    addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $client --dport 28419
    addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $client --sport 28419
  done


  ######################################################################
  # Outbound

  # SSH
  for client in trust1 trust2 trust3 trust4 trust5; do
    addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination $client --dport 22
    addToChain TCP_INPUT_ALLOWED  RETURN --protocol tcp --source      $client --sport 22
  done

  # GitHub
  addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination 204.232.175.90 --dport  22
  addToChain TCP_OUTPUT_ALLOWED RETURN --protocol tcp --destination 204.232.175.90 --dport 443

  # Whois
  addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp  --dport  43
  # HTTP
  addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp  --dport  80
  # HTTPS
# addToChain TCP_OUTPUT_ALLOWED  RETURN --protocol tcp  --dport 443

  # NTP
  addToChain UDP_OUTPUT_ALLOWED RETURN --protocol udp --dport 123
  addToChain UDP_OUTPUT_ALLOWED RETURN --protocol udp --sport 123
  addToChain UDP_INPUT_ALLOWED  RETURN --protocol udp --dport 123
  addToChain UDP_INPUT_ALLOWED  RETURN --protocol udp --sport 123
}

