#!/usr/bin/env bash

xargs -n1 iptables -N <<<'TCP_IN TCP_OUT UDP_IN UDP_OUT'

# TCP
iptables -m comment --comment "Split TCP   " -A  INPUT -p tcp -j TCP_IN
iptables -m comment --comment "Split TCP   " -A OUTPUT -p tcp -j TCP_OUT

# UDP
iptables -m comment --comment "Split UDP   " -A  INPUT -p udp -j UDP_IN
iptables -m comment --comment "Split UDP   " -A OUTPUT -p udp -j UDP_OUT

